version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: all_in_one_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: all_in_one_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: all_in_one_mailhog
    ports:
      - '1025:1025' # SMTP port
      - '8025:8025' # Web UI port
    environment:
      - MH_STORAGE=memory

volumes:
  postgres_data:
